### ISSUE TITLE
Docker container crashes unexpectedly

### ISSUE THREAD

**Issue by amirali** [danihodovic/celery-exporter#99]
Hello!
I'm using docker image on the latest version and sometimes the container randomly crashes and exports wrong data or no data at all to Prometheus. sometimes it happens with logs that I attached below and sometimes with no logs at all. I don't know if it's for the bad configuration or what. I just pass the Redis broker URI to the container with no other configuration.
```
$ docker logs -f celery_exporter

Socket error
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/waitress/channel.py", line 121, in handle_write
flush()
File "/usr/local/lib/python3.9/site-packages/waitress/channel.py", line 259, in _flush_some
num_sent = self.send(chunk)
File "/usr/local/lib/python3.9/site-packages/waitress/wasyncore.py", line 431, in send
result = self.socket.send(data)
TimeoutError: [Errno 110] Connection timed out
total open connections reached the connection limit, no longer accepting new connections
```

**Comment by altafrs77** [comment]
@amirali did you find any solution to this?
